In [1]:
##Load and combine the datas

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame()
raw_data = pd.read_csv('Indeed_Data Science.csv')
df = raw_data.drop('Unnamed: 0',axis=1)
data = df.drop('Link_Page',axis=1)

In [3]:
raw_data

,Unnamed: 0,Jobs,Companies,Locations,Salaries,Summaries,Link_Page
0,0,Accenture Big Data Engineer Consultant/Manager,Accenture,Sydney NSW,Nothing Found,Your career in Accenture Digital Accenture Big...,https://au.indeed.com/viewjob?jk=c832e75c5d42c...
1,1,Data & Insights Manager,Johnson & Johnson Family of Companies,Sydney NSW,Nothing Found,Be Vital to this role: Reporting to the Market...,https://au.indeed.com/viewjob?jk=dbf8ad4387618...
2,2,Computer Software Engineer,Blue Swimmer Consulting Pty Ltd,Edinburgh SA,Nothing Found,Job Summary You will work under a six-month co...,https://au.indeed.com/viewjob?jk=07d6cdca9234d...
3,3,"Data Analytics, Internship Program (6-12 months)",Manpower Services (Hong Kong) Limited,Australia,Nothing Found,Description: Regional Analytics is seeking a s...,https://au.indeed.com/viewjob?jk=7a2c828f62861...
4,4,Intern Developer,Technology One Limited,Brisbane QLD,Nothing Found,Work for a company where software rules! Kick ...,https://au.indeed.com/viewjob?jk=ab5ab1d78c52b...
5,5,Data Scientist,EXPERIAN,Melbourne VIC,Nothing Found,Description Utilise your programming skills to...,https://au.indeed.com/viewjob?jk=9904565d2d67f...
6,6,"Student - Data Officer, Community Planning",Moonee Valley City Council,Melbourne VIC,$32.60 - $35.20 an hour,"Student Data Officer, Community Planning Refer...",https://au.indeed.com/viewjob?jk=5a45508da8708...
7,7,Data Science Analyst,Envato,Melbourne VIC,Nothing Found,(View All Jobs) ( https://envato.com/careers/ ...,https://au.indeed.com/viewjob?jk=5aec8c62cb377...
8,8,IBM Research Australia IoT Control & Optimizat...,IBM,Melbourne VIC,Nothing Found,Job Description IBM Research Australia IoT Con...,https://au.indeed.com/viewjob?jk=8238a4bbcd239...
9,9,"Data Scientist, Google Technical Services",Google,Sydney NSW,Nothing Found,Google Technical Services: Professional Servic...,https://au.indeed.com/viewjob?jk=0edf03a7d3ecc...
10,10,Data Scientist,Munich Re,Sydney NSW,Nothing Found,As a Data Scientist you will perform a wide va...,https://au.indeed.com/viewjob?jk=d645ebbebd503...
11,11,Data Scientist,Teradata,Sydney NSW,Nothing Found,Data Scientist-175050 Description The teams at...,https://au.indeed.com/viewjob?jk=43b729efcad4a...
12,12,Data Scientist,Freelancer.com,Sydney NSW,Nothing Found,Ten-time Webby award-winning Freelancer.com is...,https://au.indeed.com/viewjob?jk=a3ceb90d3e93a...
13,13,"Regional Clinical Operations Lead, Oncology or...","Cornerstone Search Group, LLC",Sydney Central Business District NSW,Nothing Found,Regional Clinical Operations Lead | Oncology/B...,https://au.indeed.com/viewjob?jk=5ea0dcb025625...
14,14,Product Specialist,Thermo Fisher Scientific,Sydney NSW,Nothing Found,The Product Specialist is responsible for lead...,https://au.indeed.com/viewjob?jk=d8a6c96f89bf4...
15,15,Data Scientist,Equifax,Melbourne VIC,Nothing Found,Equifax powers the financial future of individ...,https://au.indeed.com/viewjob?jk=56cf46320973a...
16,16,Data Scientist,Equifax,Melbourne VIC,Nothing Found,Equifax powers the financial future of individ...,https://au.indeed.com/viewjob?jk=56cf46320973a...
17,17,Data & Insights Manager,Johnson & Johnson Family of Companies,Sydney NSW,Nothing Found,Be Vital to this role: Reporting to the Market...,https://au.indeed.com/viewjob?jk=dbf8ad4387618...
18,18,Scrum Master,Accenture,Melbourne VIC,Nothing Found,Join Accenture and help transform leading orga...,https://au.indeed.com/viewjob?jk=ecf90f577bc8b...
19,19,"Mobile Technical Solutions Consultant, Google ...",Google,Sydney NSW,Nothing Found,The Google Technical Services Velocity team’s ...,https://au.indeed.com/viewjob?jk=55fc94fe99a6e...
20,20,"Product Specialist, Google Cloud",Google,Sydney NSW,Nothing Found,When leading companies choose Google Cloud it'...,https://au.indeed.com/viewjob?jk=f82f0243e3f88...
21,21,Research Analyst,Swinburne University of Technology,Melbourne VIC,Nothing Found,The Swinburne Research Office is on a transfor...,https://au.indeed.com/viewjob?jk=859e280ac3fd6...
22,22,Lead Consultant - Data and Analytics,Atlis Consulting,Sydney NSW,Nothing Found,About Altis Altis Consulting was established i...,https://au.indeed.com/viewjob?jk=da9141e0df275...
23,23,"Technical Program Manager, Corporate Engineering",Google,Sydney NSW,Nothing Found,"Google's projects, like our users, span the gl...",https://au.indeed.com/viewjob?jk=b3b4a50122299...
24,24,Senior to Managing Consultant - Data and Analy...,Atlis Consulting,Sydney NSW,Nothing Found,About Altis Altis Consulting was established i...,https://au.indeed.com/viewjob?jk=bdedac7b14ccd...
25,25,Reporting & Insights Manager,Auto & General Insurance,Queensland,Nothing Found,: As a Reporting & Insights Manager you will w...,https://au.indeed.com/viewjob?jk=805eb63a6a3c9...
26,26,Software Engineer,Swinburne University of Technology,Melbourne VIC,Nothing Found,"In this newly created role, you will fill a se...",https://au.indeed.com/viewjob?jk=082af4c4674d7...
27,27,Lead Consultant - Data and Analytics,Altis Consulting Pty Ltd,Sydney NSW,Nothing Found,About Altis Altis Consulting was established i...,https://au.indeed.com/viewjob?jk=dd24c638733a2...
28,28,Junior Data Analyst,Football Australia,Australia,Nothing Found,footb all FFA.com.au Play Football ALDI MiniRo...,https://au.indeed.com/viewjob?jk=0b502f2d2d965...
29,29,Digital Marketing Manager,Johnson & Johnson Family of Companies,Sydney NSW,Nothing Found,An error has occurred.,https://au.indeed.com/viewjob?jk=17bce6ca9b8d1...
...,...,...,...,...,...,...,...
892,892,Clinical Research Associate,PRA Health Sciences,Australia,Nothing Found,The Clinical Research Associate (CRA) will mon...,https://au.indeed.com/viewjob?jk=d1143aa992b15...
893,893,IT Coordinator,Shenhua Australia Holdings,Tamworth NSW,Nothing Found,Job Summary Shenhua Watermark Coal Pty Ltd is ...,https://au.indeed.com/viewjob?jk=a0642dfd9cbbe...
894,894,Engineer (IP Packet Platform),Manpower Services (Hong Kong) Limited,Australia,Nothing Found,A well-established Global company is urgently ...,https://au.indeed.com/viewjob?jk=6e86681bae599...
895,895,Marketing Coordinator,Synchro Marketing Australia Pty Limited,North Sydney NSW,Nothing Found,Marketing Co-ordinator North Sydney Incentive ...,https://au.indeed.com/viewjob?jk=d543956b9f804...
896,896,Product Strategist,Tigerspike,Melbourne VIC,Nothing Found,Tigerspike Melbourne is looking for a Product ...,https://au.indeed.com/viewjob?jk=e9d9cd500c931...
897,897,Senior System Administrator - IDM/LDAP - Cloud,Oracle,North Ryde NSW,Nothing Found,Senior System Administrator - IDM/LDAP - Cloud...,https://au.indeed.com/viewjob?jk=24644eeded99b...
898,898,Mid & Senior Compositors,Rising Sun Pictures (RSP),Adelaide SA,Nothing Found,Reporting to Compositing Leads and the Head of...,https://au.indeed.com/viewjob?jk=4112d216ae67f...
899,899,Dedicated Support Engineer,Hortonworks,Melbourne VIC,Nothing Found,"As a Hadoop Dedicated Support Engineer, you wi...",https://au.indeed.com/viewjob?jk=514ae2521a30b...
900,900,QA/Software Support Officer,Bas-X,Queensland,"$50,000 - $65,000 a year",A challenging and rewarding position is availa...,https://au.indeed.com/viewjob?jk=6f0f3e090fc69...
901,901,Product Specialist,Thermo Fisher Scientific,Sydney NSW,Nothing Found,The Product Specialist is responsible for lead...,https://au.indeed.com/viewjob?jk=d8a6c96f89bf4...
902,902,Accenture Big Data Engineer Consultant/Manager,Accenture,Sydney NSW,Nothing Found,Your career in Accenture Digital Accenture Big...,https://au.indeed.com/viewjob?jk=c832e75c5d42c...
903,903,Data & Insights Manager,Johnson & Johnson Family of Companies,Sydney NSW,Nothing Found,Be Vital to this role: Reporting to the Market...,https://au.indeed.com/viewjob?jk=dbf8ad4387618...
904,904,Digital Marketing Manager,Johnson & Johnson Family of Companies,Sydney NSW,Nothing Found,Sydney based – North Ryde • Exposure to variou...,https://au.indeed.com/viewjob?jk=17bce6ca9b8d1...
905,905,Clinical Research Associate (CRA),Johnson & Johnson Family of Companies,Sydney NSW,Nothing Found,Be Vital to this role: Janssen is currently se...,https://au.indeed.com/viewjob?jk=d3de67c30b420...
906,906,Product Specialist,Thermo Fisher Scientific,Sydney NSW,Nothing Found,The Product Specialist is responsible for lead...,https://au.indeed.com/viewjob?jk=d8a6c96f89bf4...
907,907,System Admin/Engineer,Amazon.com,Sydney NSW,Nothing Found,Amazon is building some of the largest distrib...,https://au.indeed.com/viewjob?jk=d1792d767333b...
908,908,Cloud Support Engineer - Networking,Amazon.com,Sydney NSW,Nothing Found,Amazon has built a reputation for excellence w...,https://au.indeed.com/viewjob?jk=df037c0074966...
909,909,Risk Analytics Analyst/Senior Analyst,Deloitte,Melbourne VIC,Nothing Found,About the role Focusing on the biggest risks t...,https://au.indeed.com/viewjob?jk=00d0d5a733833...
910,910,Cusotmer Support Engineer,Cisco,St Leonards NSW,Nothing Found,Customer Support Engineer What You'll Do Techn...,https://au.indeed.com/viewjob?jk=01282aa6e0c95...
911,911,Mid Layout Artist / Camera TD,Rising Sun Pictures (RSP),Adelaide SA,Nothing Found,You will be responsible for assembling scenes ...,https://au.indeed.com/viewjob?jk=ef15444a76daa...
912,912,"Analysts, Senior Analysts & Managers (Data Ana...",Momenta Resourcing,Sydney Central Business District NSW,Nothing Found,Multiple ongoing positions available for exper...,https://au.indeed.com/viewjob?jk=bf08d7bfd3061...
913,913,Supply Chain Logistics Analyst (12 month Fixed...,IBM,Melbourne VIC,Nothing Found,Job Description The Supply Chain Logistics Ana...,https://au.indeed.com/viewjob?jk=a6e9845e120f5...
914,914,"Strategic Cloud Engineer, Big Data and Machine...",Google,Sydney NSW,Nothing Found,Google Technical Services: Professional Servic...,https://au.indeed.com/viewjob?jk=f78504860020c...
915,915,Big Data Engineer,SAI Global,Sydney NSW,Nothing Found,The Data & Analytics team at SAI Global are em...,https://au.indeed.com/viewjob?jk=8103908857271...
916,916,Data Warehousing/Business Intelligence Consultant,AIESEC,Perth WA,Nothing Found,Select and design the data warehouse architect...,https://au.indeed.com/viewjob?jk=8a59d3dc2afcf...
917,917,Accenture Big Data Engineer Consultant/Manager,Accenture,Sydney NSW,Nothing Found,Your career in Accenture Digital Accenture Big...,https://au.indeed.com/viewjob?jk=c832e75c5d42c...
918,918,Data & Insights Manager,Johnson & Johnson Family of Companies,Sydney NSW,Nothing Found,Be Vital to this role: Reporting to the Market...,https://au.indeed.com/viewjob?jk=dbf8ad4387618...
919,919,Data Scientist,Equifax,Melbourne VIC,Nothing Found,Equifax powers the financial future of individ...,https://au.indeed.com/viewjob?jk=56cf46320973a...
920,920,Clinical Research Associate (CRA),Johnson & Johnson Family of Companies,Sydney NSW,Nothing Found,Failed to scrape,No Links
921,921,Digital Marketing Manager,Johnson & Johnson Family of Companies,Sydney NSW,Nothing Found,Failed to scrape,https://jobs.jnj.com/jobs/1700206494W/Digital-...

In [4]:
data.head()

,Jobs,Companies,Locations,Salaries,Summaries
0,Accenture Big Data Engineer Consultant/Manager,Accenture,Sydney NSW,Nothing Found,Your career in Accenture Digital Accenture Big...
1,Data & Insights Manager,Johnson & Johnson Family of Companies,Sydney NSW,Nothing Found,Be Vital to this role: Reporting to the Market...
2,Computer Software Engineer,Blue Swimmer Consulting Pty Ltd,Edinburgh SA,Nothing Found,Job Summary You will work under a six-month co...
3,"Data Analytics, Internship Program (6-12 months)",Manpower Services (Hong Kong) Limited,Australia,Nothing Found,Description: Regional Analytics is seeking a s...
4,Intern Developer,Technology One Limited,Brisbane QLD,Nothing Found,Work for a company where software rules! Kick ...

In [5]:
def input_data(filename):
    raw_data = pd.read_csv(filename,index_col=None)
    df = raw_data.drop('Unnamed: 0',axis=1)
    df = df.drop('Link_Page',axis=1)
    data1 = pd.concat([data,df], axis=0)
    return data1

In [6]:
files = ['Indeed_Data Science1.csv','Indeed_Data Science3.csv','Indeed_Data Scientist.csv','Indeed_Data Engineer.csv',
        'Indeed_Business Analyst.csv','Indeed_Business Analyst1.csv','Indeed_Data Analyst.csv','Indeed_Machine Learning.csv']

In [7]:
for file in files:
    data = input_data(file)

In [876]:
#Overall data
data.shape

(8270, 5)

In [9]:
data.reset_index(inplace=True)

In [10]:
data.drop('index',axis=1,inplace=True)

In [11]:
data.shape

(8270, 5)

In [12]:
##Cleaning the data

In [13]:
#we choose only those who have salary
salaries = data[data.Salaries.values != 'Nothing Found']

In [14]:
salaries.shape

(1893, 5)

In [80]:
salaries.Salaries = salaries.Salaries.str.replace(',', '').str.replace('$', '')

In [850]:
job = 'Senior Data Scientist'

In [851]:
salaries[salaries.Jobs.values == job].Companies.value_counts()

Opus Recruitment Solutions    2
Morgan McKinley               1
Name: Companies, dtype: int64

In [852]:
salaries[salaries.Jobs.values == job].Locations.value_counts()

Sydney NSW                              2
Sydney Central Business District NSW    1
Name: Locations, dtype: int64

In [853]:
a = salaries[salaries.Jobs.values == job]
#a = a[a.Companies.values == 'Kelly Howard Recruitment ']
#a = a[a.Locations.values == 'Australia']
a

,Jobs,Companies,Locations,Salaries,Summaries
1697,Senior Data Scientist,Opus Recruitment Solutions,Sydney NSW,100000 - 200000 a year,You will be helping businesses to derive value...
2839,Senior Data Scientist,Morgan McKinley,Sydney Central Business District NSW,160000 - 180000 a year,Role Senior Data Scientist Salary up to $180k ...
8023,Senior Data Scientist,Opus Recruitment Solutions,Sydney NSW,140000 - 180000 a year,Tech driven company within Fintech market Chan...

In [854]:
list1 = a[a.index != 880]
list1 = list1.index
list1

Int64Index([1697, 2839, 8023], dtype='int64')

In [843]:
salaries = salaries.drop(list1)

In [844]:
#now thats good
dups = salaries[salaries.Jobs.duplicated() & salaries.Companies.duplicated() & salaries.Locations.duplicated()]
dups.Jobs.value_counts()

Business Analyst                                                  9
Senior Business Analyst                                           6
Test Analyst                                                      5
System Analyst                                                    2
Senior Data Scientist                                             2
Software Engineer                                                 2
Business Process Analyst                                          2
Data Analyst                                                      2
Agile Business Analyst                                            2
Finance Analyst                                                   2
Big Data Engineer                                                 2
Senior Software Engineer                                          2
Information and Cyber Security Analyst                            1
2 x Research Assistants                                           1
University Senior Research Associate - Computer Science           1
Principal Business Analyst                                        1
PhD Scholarship Opportunity in Biomarkers of Sleep Loss           1
Data Scientist                                                    1
Business analyst                                                  1
Digital Performance/Data Analyst                                  1
IT Engineer - North Shore - Permanent                             1
Compensation Analyst ($30K above per month)                       1
Business Support Team Leader                                      1
Research Associate, Bioinformatics                                1
SENIOR BUSINESS ANALYST                                           1
Software Engineer (Java/Spark/Scala) | Bespoke Analytics Tools    1
MID/SNR DATA SCIENTIST                                            1
Associate Product Manager                                         1
Data Migration Specialist - Data/Business                         1
Business Development Manager                                      1
                                                                 ..
Senior Analyst | Analytics | Boutique Market Research Agency      1
Full Stack Developer                                              1
Backend JVM Engineer | Kotlin                                     1
Senior Lecturer (NMR)                                             1
Junior Analyst                                                    1
Geospatial Modeller                                               1
Senior Application Developer - Brisbane based                     1
Business/Information Analyst                                      1
Data Engineer                                                     1
Horticultural Engagement Officer                                  1
Business Systems Analyst (S12)                                    1
Senior Consultant | Quantitative | Market Research                1
ICT Business Analyst                                              1
Junior Data Analyst (SAS)                                         1
Senior Application Developer (Javascript)                         1
Analyst                                                           1
Customer Data Scientist                                           1
Research Analyst                                                  1
Software Designer                                                 1
Research Analyst (Real Estate Fund Manager)                       1
Town Planner                                                      1
Lead Data Engineer / Developer                                    1
Biostatistician (Research Officer)                                1
Intelligence Analyst                                              1
Data Scientist (Loyalty Marketing)                                1
Board Certified Behaviour Analyst                                 1
Insights Analyst |Statistical |Tableau |Power BI                  1
Scheme Data Analyst                                               1
IT Business Analyst - URGENT                                      1
Business Analyst Retail                                           1
Name: Jobs, Length: 112, dtype: int64

In [855]:
salaries.shape

(728, 5)

In [860]:
salaries.to_csv('Clean.csv')

In [24]:
#convert salaries to yearly rate based on https://www.paycalculator.com.au

In [867]:
salaries.reset_index(inplace=True)

In [868]:
salaries.drop('index',axis=1,inplace=True)
salaries.head()

,Jobs,Companies,Locations,Salaries,Summaries
0,"Student - Data Officer, Community Planning",Moonee Valley City Council,Melbourne VIC,32.60 - 35.20 an hour,"Student Data Officer, Community Planning Refer..."
1,Solutions Architect,Pythian,Sydney NSW,150000 - 180000 a year,Job Summary Why Pythian? Pythian is a global I...
2,"Manager, Insights",State Trustees Limited,Melbourne VIC,91610 - 141684 a year,Located at our Head Office in Footscray (10 mi...
3,PhD Scholarship – Big Data Analytics for Oil D...,Swinburne University of Technology,Melbourne VIC,25849 a year,"Faculty of Science, Engineering and Technology..."
4,STRUCTURAL TECHNOLOGY SPECIALIST,VicRoads,Kew East VIC,106817 - 129960 a year,About VicRoads Victoria has embarked on a once...

In [869]:
#rep = ['a year','a day','a week','an hour','a month']
for row in range(len(salaries)):
    value = salaries.iloc[row,3]

    if value.find('a day') != -1:
        newvalue = value.replace('a day','')
        newvalue = newvalue.replace(' ','')
        if value.find('-') != -1:
            values = newvalue.split('-')
            newvalue = (float(values[0])+float(values[1]))/2
        newvalue = (float(newvalue) * 5) * 250
        salaries.iloc[row,3] = newvalue
    if value.find('a week') != -1:
        newvalue = value.replace('a week','')
        newvalue = newvalue.replace(' ','')
        if value.find('-') != -1:
            values = newvalue.split('-')
            newvalue = (float(values[0])+float(values[1]))/2
        newvalue = float(newvalue) * 52
        salaries.iloc[row,3] = newvalue
    if value.find('a year') != -1:
        newvalue = value.replace('a year','')
        newvalue = newvalue.replace(' ','')
        if value.find('-') != -1:
            values = newvalue.split('-')
            newvalue = (float(values[0])+float(values[1]))/2
        salaries.iloc[row,3] = float(newvalue)
    if value.find('an hour') != -1:
        newvalue = value.replace('an hour','')
        newvalue = newvalue.replace(' ','')
        if value.find('-') != -1:
            values = newvalue.split('-')
            newvalue = (float(values[0])+float(values[1]))/2
        newvalue = ((float(newvalue) * 8) * 5)*250
        salaries.iloc[row,3] = newvalue
    if value.find('a month') != -1:
        newvalue = value.replace('a month','')
        newvalue = newvalue.replace(' ','')
        if value.find('-') != -1:
            values = newvalue.split('-')
            newvalue = (float(values[0])+float(values[1]))/2
        newvalue = float(newvalue) * 12
        salaries.iloc[row,3] = newvalue

In [870]:
#convert salaries to float
salaries.Salaries = salaries.Salaries.astype(float)

In [871]:
salaries.dtypes

Jobs          object
Companies     object
Locations     object
Salaries     float64
Summaries     object
dtype: object

In [872]:
salaries.head(10)

,Jobs,Companies,Locations,Salaries,Summaries
0,"Student - Data Officer, Community Planning",Moonee Valley City Council,Melbourne VIC,339000.0,"Student Data Officer, Community Planning Refer..."
1,Solutions Architect,Pythian,Sydney NSW,165000.0,Job Summary Why Pythian? Pythian is a global I...
2,"Manager, Insights",State Trustees Limited,Melbourne VIC,116647.0,Located at our Head Office in Footscray (10 mi...
3,PhD Scholarship – Big Data Analytics for Oil D...,Swinburne University of Technology,Melbourne VIC,25849.0,"Faculty of Science, Engineering and Technology..."
4,STRUCTURAL TECHNOLOGY SPECIALIST,VicRoads,Kew East VIC,118388.5,About VicRoads Victoria has embarked on a once...
5,Senior Technical Specialist,Tasmanian Government,Hobart TAS,93777.0,Award/Classification: Tasmanian State Service ...
6,Executive Transformation Program Designer,CSIRO,Sydney NSW,118500.0,Make an impact through designing an educationa...
7,Operations Coordinator,Macquarie University,Macquarie University NSW,94133.5,Macquarie is the university of pioneering mind...
8,Research Associate,University Of Western Australia,Crawley WA,79374.5,Faculty of Engineering and Mathematical Scienc...
9,Mapping Analyst,"Department of Economic Development, Jobs, Tran...",Melbourne City Centre VIC,86829.0,"$81,354 - $92,304 (Plus Superannuation) Ongoin..."

In [873]:
#saved and ready to use
salaries.to_csv('Cleaned_salary.csv')